### ISSUE TITLE
Incorperate into Vue

### ISSUE THREAD

**Issue by bakkertjebrood** [kiruh/ckeditor5-placeholder#1]
I'm trying to get this plugin to work in a Vue component. I am using the standard CKeditor5 vue component but cannot seem to get it to work and keep getting 

> ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated.

I also tried using this in a custom build, not to no avail. It is telling me unexpected error. Do you have any idea how to proceed?

**Comment by kiruh** [comment]
It's shown as a warning but everything else is fine. You can see in the [demo of this project](https://ckeditor5-placeholder.netlify.com/) that there's an error in console but the editor works fine.

Here's what I've found in documentation:
https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules

**Comment by kiruh** [comment]
By the way, did you find some workaround for that in Vue?

**Comment by bakkertjebrood** [comment]
I did not find a workaround and decided to ditch CKeditor and switch to Trumbowyg.

**Comment by zameji** [comment]
I just ran into the same issue and was able to resolve it. Turns out, the issue boiled down to having multiple versions of the same ckeditor-packages installed. Concretely:

-  @ckeditor/ckeditor5-core
-  @ckeditor/ckeditor5-engine
-  @ckeditor/ckeditor5-ui
-  @ckeditor/ckeditor5-utils

I had to override the installed packages manually in the package.json in our repository using [npm resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/). Once only one copy of each package existed, everything started to work. (with ckeditor5 ^16.0.0)

**Comment by kiruh** [comment]
@zameji do I need to update package.json in that package?

**Comment by zameji** [comment]
It shouldn't do any harm. Though I don't think this is a problem on your side: you allow versions above v12, so I don't know why did yarn decide that v16 is not good enough.

**Comment by kiruh** [comment]
Fixed in [v1.0.4](https://github.com/kiruh/ckeditor5-placeholder/releases/tag/v1.0.4)
